#!/usr/bin/env python3

import os
import socket


ip = input("Введите IP: ")


client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect((ip, 1303))


def receive():
    while True:
        try:
            message = client.recv(1024).decode('ascii')
            print(message)
        except:
            print("Error!")
        client.close()
        break

os.system('clear')

receive()